server:
  port: 8081
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
      
spring:
  application:
    name: eCommerce-gateway
  cloud:
    gateway:
      routes:
      - id: order
        uri: lb://order-service
        predicates:
        - Path=/order/**
      - id: order
        uri: lb://product-service
        predicates:
        - Path=/product/**
